### ISSUE TITLE
Design subway lines

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#10]
#2

**Comment by stinerz** [comment]
![mapttc](https://cloud.githubusercontent.com/assets/10968325/6427927/564ae634-bf5d-11e4-9f9b-784154f7da06.png)

**Comment by stinerz** [comment]
![bb8ed152-c1cb-11e4-8797-af97febf1cad 1](https://cloud.githubusercontent.com/assets/10968325/6487704/b72892fc-c260-11e4-9b5f-9d9729f21ca6.png)

**Comment by trapeznikov** [comment]
![763395d0-c260-11e4-9565-085ca8a0d5d0](https://cloud.githubusercontent.com/assets/10961578/6488512/f73f3ee0-c265-11e4-9ceb-9282b02b1107.png)
