### ISSUE TITLE
Code buttons for each station

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#11]
#2

**Comment by JohnnyChenh** [comment]
http://jsfiddle.net/sqJtr/

**Comment by JohnnyChenh** [comment]
SubwayImageMapCorrdinate	template
https://github.com/TeamTrapeznikov/TTC_Subway_Delays/blob/master/SubwayImageMapCorrdinate
corrdinate still need to be input
