### ISSUE TITLE
Design and normalize a database

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#12]
#2

**Comment by shivanimgupta** [comment]
![image](https://cloud.githubusercontent.com/assets/10970473/6432508/21f7da70-c022-11e4-83f2-7390b46a7507.png)

**Comment by shivanimgupta** [comment]
![image](https://cloud.githubusercontent.com/assets/10970473/6432669/c68da204-c027-11e4-8897-e6294e5983fc.png)

**Comment by shivanimgupta** [comment]
![image](https://cloud.githubusercontent.com/assets/10970473/6432674/e7514018-c027-11e4-89bd-0d7b8533ade7.png)

**Comment by shivanimgupta** [comment]
![image](https://cloud.githubusercontent.com/assets/10970473/6433167/8f9ce01c-c035-11e4-88b8-d968f5ce08a8.png)
