### ISSUE TITLE
Script tables

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#13]
#2

**Comment by shivanimgupta** [comment]
https://github.com/TeamTrapeznikov/TTC_Subway_Delays/commit/fc7b9f56451bb4b3a1ccdebc2b8d4665bf934c1d

**Comment by shivanimgupta** [comment]
Task #13 done

fc7b9f56451bb4b3a1ccdebc2b8d4665bf934c1d
