### ISSUE TITLE
Design subway station signs

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#30]
#2

**Comment by stinerz** [comment]
![mapttc](https://cloud.githubusercontent.com/assets/10968325/6427928/649407c0-bf5d-11e4-96a1-d869d2de6501.png)

**Comment by stinerz** [comment]
![bb8ed152-c1cb-11e4-8797-af97febf1cad 1](https://cloud.githubusercontent.com/assets/10968325/6487653/763395d0-c260-11e4-9565-085ca8a0d5d0.png)

**Comment by trapeznikov** [comment]
![763395d0-c260-11e4-9565-085ca8a0d5d0](https://cloud.githubusercontent.com/assets/10961578/6488482/d822d59e-c265-11e4-98fa-b2865fa0e872.png)

**Comment by stinerz** [comment]
![subwaymap](https://cloud.githubusercontent.com/assets/10968325/6548052/9cb4fe64-c5c2-11e4-8156-90fb24200f37.png)
