### ISSUE TITLE
Design sorting buttons

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#57]
#52

**Comment by JohnnyChenh** [comment]
alert default
![alert default](https://cloud.githubusercontent.com/assets/10988724/6657637/16fa4a3e-cb28-11e4-9e72-0d7f227f6514.jpg)
alert hover
![alert hover](https://cloud.githubusercontent.com/assets/10988724/6657635/16f9ef62-cb28-11e4-8002-9aa5271cf115.jpg)
alert press
![alert press](https://cloud.githubusercontent.com/assets/10988724/6657636/16fa3c42-cb28-11e4-8014-c7188bf79ccc.jpg)
alphabetically default
![alphabetically default](https://cloud.githubusercontent.com/assets/10988724/6657639/16fbfff0-cb28-11e4-9453-542337007097.jpg)
alphabetically hover
![alphabetically hover](https://cloud.githubusercontent.com/assets/10988724/6657634/16f9d6f8-cb28-11e4-90c8-b9e76f1cda4b.jpg)
alphabetically press
![alphabetically press](https://cloud.githubusercontent.com/assets/10988724/6657638/16faf2d6-cb28-11e4-9012-56289fb2d285.jpg)
number hover
![number hover](https://cloud.githubusercontent.com/assets/10988724/6657640/17045a06-cb28-11e4-96ac-454aff380d15.jpg)
number press
![number press](https://cloud.githubusercontent.com/assets/10988724/6657641/1704f628-cb28-11e4-84bb-232e4ed00915.jpg)
numberdefault
![numberdefault](https://cloud.githubusercontent.com/assets/10988724/6657642/170517c0-cb28-11e4-8f97-d6980a004fa5.jpg)
