### ISSUE TITLE
Implement alert post in subway map

### ISSUE THREAD

**Issue by trapeznikov** [TeamTrapeznikov/TTC_Subway_Delays#64]
#53

**Comment by shivanimgupta** [comment]
Task #64 completed successfully.
35a161bdd4e6d7864e6b593f5011678321a459f6
29ec2411cb764b62881ec5919f4571b5a96438d9
271ac10f98e145c5cfdee970d5c970fb37494770
1fc9e633c97a313e1545afd05aacfcb18325bd01
